# ----
# Site

title: Aviator
description: Jekyll.
url: https://example.com
google_analytics_key:

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# -----
# Build


# -----------
# CloudCannon

version: 3.0.3
